services:
  phdmanager:
    image: ${DOCKER_REGISTRY-}phdmanager
    build:
      context: .
      dockerfile: PhDManager/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - phdmanager.db

  phdmanager.db:
    image: postgres:17.0
    environment:
      POSTGRES_PASSWORD: phdmanager
      POSTGRES_DB: phdmanager
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: