services:
  phdmanager:
    image: ${DOCKER_REGISTRY-}phdmanager
    build:
      context: .
      dockerfile: PhDManager/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - phdmanager.db
      - phdmanager.proxy

  phdmanager.db:
    image: postgres:17.0
    environment:
      POSTGRES_USER: phdmanager
      POSTGRES_PASSWORD: phdmanager
      POSTGRES_DB: phdmanager
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  phdmanager.proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxy-data:/data
      - letsencrypt:/etc/letsencrypt

volumes:
  db-data:
  proxy-data:
  letsencrypt:
  
networks:
  default:
    external: true
    name: proxy