// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhDManager.Data;

#nullable disable

namespace PhDManager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250227143613_IndividualPlanRelations")]
    partial class IndividualPlanRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IndividualPlanSubject", b =>
                {
                    b.Property<int>("IndividualPlansId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("integer");

                    b.HasKey("IndividualPlansId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("IndividualPlanSubject");
                });

            modelBuilder.Entity("IndividualPlanSubject1", b =>
                {
                    b.Property<int>("OptionalIndividualPlansId")
                        .HasColumnType("integer");

                    b.Property<int>("OptionalSubjectsId")
                        .HasColumnType("integer");

                    b.HasKey("OptionalIndividualPlansId", "OptionalSubjectsId");

                    b.HasIndex("OptionalSubjectsId");

                    b.ToTable("IndividualPlanSubject1");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PhDManager.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PhDManager.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PhDManager.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("PhDManager.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExternalId1")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThesisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId1");

                    b.HasIndex("ThesisId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PhDManager.Models.External", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("External");
                });

            modelBuilder.Entity("PhDManager.Models.IndividualPlan", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DissertationExamDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DissertationSubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StudyEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StudyStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ThematicAreas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WrittenThesisRecommendedLectures")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WrittenThesisRecommendedStudyLiterature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WrittenThesisRequiredStudyLiterature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WrittenThesisTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IndividualPlans");
                });

            modelBuilder.Entity("PhDManager.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("PhDManager.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EndSchoolYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<string>("StartSchoolYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StudyProgramId")
                        .HasColumnType("integer");

                    b.Property<int?>("ThesisInterestId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudyProgramId");

                    b.HasIndex("ThesisInterestId");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PhDManager.Models.StudyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudyFieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("ThesisSubjects")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("StudyPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AI",
                            Name = "Aplikovaná informatika",
                            StudyFieldName = "Informatika",
                            ThesisSubjects = new[] { "Matematické princípy informatiky", "Teória a metodológia aplikovanej informatiky", "Predmet špecializácie" }
                        },
                        new
                        {
                            Id = 2,
                            Code = "M",
                            Name = "Manažment",
                            StudyFieldName = "Ekonómia a manažment",
                            ThesisSubjects = new[] { "Metodológia výskumu v manažmente", "Manažérske teórie", "Predmet špecializácie" }
                        });
                });

            modelBuilder.Entity("PhDManager.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudyProgramId")
                        .HasColumnType("integer");

                    b.Property<char?>("Variant")
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsRequired = true,
                            Name = "Matematické princípy informatiky - A: Deterministické metódy",
                            Semester = "zimný",
                            StudyProgramId = 1,
                            Variant = 'A'
                        },
                        new
                        {
                            Id = 2,
                            IsRequired = true,
                            Name = "Matematické princípy informatiky - B: Stochastické metódy",
                            Semester = "zimný",
                            StudyProgramId = 1,
                            Variant = 'B'
                        },
                        new
                        {
                            Id = 3,
                            IsRequired = true,
                            Name = "Teória a metodológia aplikovanej informatiky - A: Znalostné systémy a algoritmy",
                            Semester = "letný",
                            StudyProgramId = 1,
                            Variant = 'A'
                        },
                        new
                        {
                            Id = 4,
                            IsRequired = true,
                            Name = "Teória a metodológia aplikovanej informatiky - B: Výpočtová inteligencia",
                            Semester = "letný",
                            StudyProgramId = 1,
                            Variant = 'B'
                        },
                        new
                        {
                            Id = 5,
                            IsRequired = true,
                            Name = "Predmet špecializácie",
                            Semester = "letný",
                            StudyProgramId = 1
                        },
                        new
                        {
                            Id = 6,
                            IsRequired = true,
                            Name = "Manažérske teórie",
                            Semester = "zimný",
                            StudyProgramId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsRequired = true,
                            Name = "Metodológia výskumu v manažmente",
                            Semester = "zimný",
                            StudyProgramId = 2
                        },
                        new
                        {
                            Id = 8,
                            IsRequired = true,
                            Name = "Predmet špecializácie",
                            Semester = "letný",
                            StudyProgramId = 2
                        });
                });

            modelBuilder.Entity("PhDManager.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("PhDManager.Models.Thesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DailyStudy")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEnglish")
                        .HasColumnType("text");

                    b.Property<bool>("ExternalStudy")
                        .HasColumnType("boolean");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("ResearchTask")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResearchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificContribution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificProgress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SolutionResults")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("StudyProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("integer");

                    b.Property<int?>("SupervisorSpecialistId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("StudyProgramId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("SupervisorSpecialistId");

                    b.ToTable("Theses");
                });

            modelBuilder.Entity("IndividualPlanSubject", b =>
                {
                    b.HasOne("PhDManager.Models.IndividualPlan", null)
                        .WithMany()
                        .HasForeignKey("IndividualPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhDManager.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IndividualPlanSubject1", b =>
                {
                    b.HasOne("PhDManager.Models.IndividualPlan", null)
                        .WithMany()
                        .HasForeignKey("OptionalIndividualPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhDManager.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("OptionalSubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhDManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhDManager.Models.Address", b =>
                {
                    b.HasOne("PhDManager.Models.Student", "Student")
                        .WithOne("Address")
                        .HasForeignKey("PhDManager.Models.Address", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PhDManager.Models.Admin", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", "User")
                        .WithOne("Admin")
                        .HasForeignKey("PhDManager.Models.Admin", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhDManager.Models.Comment", b =>
                {
                    b.HasOne("PhDManager.Models.External", "External")
                        .WithMany("Comments")
                        .HasForeignKey("ExternalId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhDManager.Models.Thesis", "Thesis")
                        .WithMany("Comments")
                        .HasForeignKey("ThesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("External");

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("PhDManager.Models.External", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", "User")
                        .WithOne("External")
                        .HasForeignKey("PhDManager.Models.External", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhDManager.Models.IndividualPlan", b =>
                {
                    b.HasOne("PhDManager.Models.Student", "Student")
                        .WithOne("IndividualPlan")
                        .HasForeignKey("PhDManager.Models.IndividualPlan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PhDManager.Models.Student", b =>
                {
                    b.HasOne("PhDManager.Models.StudyProgram", "StudyProgram")
                        .WithMany()
                        .HasForeignKey("StudyProgramId");

                    b.HasOne("PhDManager.Models.Thesis", "ThesisInterest")
                        .WithMany("InterestedStudents")
                        .HasForeignKey("ThesisInterestId");

                    b.HasOne("PhDManager.Data.ApplicationUser", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId");

                    b.Navigation("StudyProgram");

                    b.Navigation("ThesisInterest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhDManager.Models.Subject", b =>
                {
                    b.HasOne("PhDManager.Models.StudyProgram", "StudyProgram")
                        .WithMany("Subjects")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("PhDManager.Models.Teacher", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("PhDManager.Models.Teacher", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhDManager.Models.Thesis", b =>
                {
                    b.HasOne("PhDManager.Models.Student", "Student")
                        .WithOne("Thesis")
                        .HasForeignKey("PhDManager.Models.Thesis", "StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhDManager.Models.StudyProgram", "StudyProgram")
                        .WithMany("Thesis")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhDManager.Models.Teacher", "Supervisor")
                        .WithMany("Theses")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhDManager.Models.Teacher", "SupervisorSpecialist")
                        .WithMany("SpecialistTheses")
                        .HasForeignKey("SupervisorSpecialistId");

                    b.Navigation("Student");

                    b.Navigation("StudyProgram");

                    b.Navigation("Supervisor");

                    b.Navigation("SupervisorSpecialist");
                });

            modelBuilder.Entity("PhDManager.Data.ApplicationUser", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("External");

                    b.Navigation("Students");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PhDManager.Models.External", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PhDManager.Models.Student", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("IndividualPlan");

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("PhDManager.Models.StudyProgram", b =>
                {
                    b.Navigation("Subjects");

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("PhDManager.Models.Teacher", b =>
                {
                    b.Navigation("SpecialistTheses");

                    b.Navigation("Theses");
                });

            modelBuilder.Entity("PhDManager.Models.Thesis", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("InterestedStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
