// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhDManager.Data;

#nullable disable

namespace PhDManager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250213152032_StudyField")]
    partial class StudyField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IndividualPlanSubject", b =>
                {
                    b.Property<int>("IndividualPlansId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("integer");

                    b.HasKey("IndividualPlansId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("IndividualPlanSubject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PhDManager.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("IndividualPlanId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int?>("StudyProgramId")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IndividualPlanId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PhDManager.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Address");
                });

            modelBuilder.Entity("PhDManager.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThesisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ThesisId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("PhDManager.Models.IndividualPlan", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DissertationExamDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DissertationSubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StudyEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("IndividualPlan");
                });

            modelBuilder.Entity("PhDManager.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("PhDManager.Models.StudyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudyFieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudyPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AI",
                            Name = "Aplikovaná informatika",
                            StudyFieldName = "Informatika"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MAN",
                            Name = "Manažment",
                            StudyFieldName = "Ekonómia a manažment"
                        });
                });

            modelBuilder.Entity("PhDManager.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudyProgramId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MPI",
                            Credits = 5,
                            Name = "Matematické princípy informatiky",
                            Semester = "zimný",
                            StudyProgramId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "TM AI",
                            Credits = 5,
                            Name = "Teória a metodológia aplikovanej informatiky",
                            Semester = "zimný",
                            StudyProgramId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "JAD1",
                            Credits = 5,
                            Name = "Jazyk anglický PhD. 1",
                            Semester = "zimný",
                            StudyProgramId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "DPR1",
                            Credits = 5,
                            Name = "Dizertačný projekt 1",
                            Semester = "zimný",
                            StudyProgramId = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "VPub1",
                            Credits = 10,
                            Name = "Vedecká a publikačná činnosť 1",
                            Semester = "letný",
                            StudyProgramId = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "JAD2",
                            Credits = 5,
                            Name = "Jazyk anglický PhD. 2",
                            Semester = "letný",
                            StudyProgramId = 1
                        },
                        new
                        {
                            Id = 7,
                            Code = "DPR2",
                            Credits = 5,
                            Name = "Dizertačný projekt 2",
                            Semester = "letný",
                            StudyProgramId = 1
                        },
                        new
                        {
                            Id = 8,
                            Code = "ManT",
                            Credits = 5,
                            Name = "Manažérske teórie",
                            Semester = "zimný",
                            StudyProgramId = 2
                        },
                        new
                        {
                            Id = 9,
                            Code = "MVM",
                            Credits = 5,
                            Name = "Metodológia výskumu v manažmente",
                            Semester = "zimný",
                            StudyProgramId = 2
                        },
                        new
                        {
                            Id = 10,
                            Code = "JAD1",
                            Credits = 5,
                            Name = "Jazyk anglický PhD. 1",
                            Semester = "zimný",
                            StudyProgramId = 2
                        },
                        new
                        {
                            Id = 11,
                            Code = "DPR1",
                            Credits = 5,
                            Name = "Dizertačný projekt 1",
                            Semester = "zimný",
                            StudyProgramId = 2
                        },
                        new
                        {
                            Id = 12,
                            Code = "VPub1",
                            Credits = 10,
                            Name = "Vedecká a publikačná činnosť 1",
                            Semester = "letný",
                            StudyProgramId = 2
                        },
                        new
                        {
                            Id = 13,
                            Code = "JAD2",
                            Credits = 5,
                            Name = "Jazyk anglický PhD. 2",
                            Semester = "letný",
                            StudyProgramId = 2
                        },
                        new
                        {
                            Id = 14,
                            Code = "DPR2",
                            Credits = 5,
                            Name = "Dizertačný projekt 2",
                            Semester = "letný",
                            StudyProgramId = 2
                        });
                });

            modelBuilder.Entity("PhDManager.Models.Thesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DailyStudy")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEnglish")
                        .HasColumnType("text");

                    b.Property<bool>("ExternalStudy")
                        .HasColumnType("boolean");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("ResearchTask")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResearchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificContribution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScientificProgress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SolutionResults")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudyProgramId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("SubjectNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudyProgramId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Theses");
                });

            modelBuilder.Entity("IndividualPlanSubject", b =>
                {
                    b.HasOne("PhDManager.Models.IndividualPlan", null)
                        .WithMany()
                        .HasForeignKey("IndividualPlansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhDManager.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhDManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhDManager.Data.ApplicationUser", b =>
                {
                    b.HasOne("PhDManager.Models.IndividualPlan", "IndividualPlan")
                        .WithOne("User")
                        .HasForeignKey("PhDManager.Data.ApplicationUser", "IndividualPlanId");

                    b.HasOne("PhDManager.Models.StudyProgram", "StudyProgram")
                        .WithMany()
                        .HasForeignKey("StudyProgramId");

                    b.Navigation("IndividualPlan");

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("PhDManager.Models.Address", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", "User")
                        .WithOne("Address")
                        .HasForeignKey("PhDManager.Models.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhDManager.Models.Comment", b =>
                {
                    b.HasOne("PhDManager.Data.ApplicationUser", "Reviewer")
                        .WithMany("Comments")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhDManager.Models.Thesis", "Thesis")
                        .WithMany("Comments")
                        .HasForeignKey("ThesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("PhDManager.Models.IndividualPlan", b =>
                {
                    b.HasOne("PhDManager.Models.Thesis", "Thesis")
                        .WithOne("IndividualPlan")
                        .HasForeignKey("PhDManager.Models.IndividualPlan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("PhDManager.Models.Subject", b =>
                {
                    b.HasOne("PhDManager.Models.StudyProgram", "StudyProgram")
                        .WithMany("Subjects")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyProgram");
                });

            modelBuilder.Entity("PhDManager.Models.Thesis", b =>
                {
                    b.HasOne("PhDManager.Models.StudyProgram", "StudyProgram")
                        .WithMany("Thesis")
                        .HasForeignKey("StudyProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhDManager.Data.ApplicationUser", "Supervisor")
                        .WithMany("SupervisorTheses")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyProgram");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("PhDManager.Data.ApplicationUser", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Comments");

                    b.Navigation("SupervisorTheses");
                });

            modelBuilder.Entity("PhDManager.Models.IndividualPlan", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("PhDManager.Models.StudyProgram", b =>
                {
                    b.Navigation("Subjects");

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("PhDManager.Models.Thesis", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("IndividualPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
