//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhDManager.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhDManager.Locales.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string SemesterSummer {
            get {
                return ResourceManager.GetString("SemesterSummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string SemesterWinter {
            get {
                return ResourceManager.GetString("SemesterWinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string StudentStateEnded {
            get {
                return ResourceManager.GetString("StudentStateEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupted.
        /// </summary>
        public static string StudentStateInterrupted {
            get {
                return ResourceManager.GetString("StudentStateInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study.
        /// </summary>
        public static string StudentStateStudy {
            get {
                return ResourceManager.GetString("StudentStateStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfinished.
        /// </summary>
        public static string StudentStateUnfinished {
            get {
                return ResourceManager.GetString("StudentStateUnfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string StudyFormDaily {
            get {
                return ResourceManager.GetString("StudyFormDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string StudyFormExternal {
            get {
                return ResourceManager.GetString("StudyFormExternal", resourceCulture);
            }
        }
    }
}
