//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhDManager.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhDManager.Locales.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllPeople {
            get {
                return ResourceManager.GetString("AllPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved email.
        /// </summary>
        public static string ApprovedEmail {
            get {
                return ResourceManager.GetString("ApprovedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment.
        /// </summary>
        public static string CommentEdit {
            get {
                return ResourceManager.GetString("CommentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments count.
        /// </summary>
        public static string CommentsCount {
            get {
                return ResourceManager.GetString("CommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation password.
        /// </summary>
        public static string ConfirmationPassword {
            get {
                return ResourceManager.GetString("ConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create registration.
        /// </summary>
        public static string CreateRegistration {
            get {
                return ResourceManager.GetString("CreateRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadlines.
        /// </summary>
        public static string Deadlines {
            get {
                return ResourceManager.GetString("Deadlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissertation thesis edit.
        /// </summary>
        public static string DisserationThesisEdit {
            get {
                return ResourceManager.GetString("DisserationThesisEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissertation theses.
        /// </summary>
        public static string DissertationTheses {
            get {
                return ResourceManager.GetString("DissertationTheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My dissertation theses.
        /// </summary>
        public static string DissertationThesesMy {
            get {
                return ResourceManager.GetString("DissertationThesesMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissertation thesis.
        /// </summary>
        public static string DissertationThesis {
            get {
                return ResourceManager.GetString("DissertationThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dissertation thesis.
        /// </summary>
        public static string DissertationThesisAdd {
            get {
                return ResourceManager.GetString("DissertationThesisAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissertation thesis assignment.
        /// </summary>
        public static string DissertationThesisAssignment {
            get {
                return ResourceManager.GetString("DissertationThesisAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissertation thesis classification.
        /// </summary>
        public static string DissertationThesisClassification {
            get {
                return ResourceManager.GetString("DissertationThesisClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete dissertation thesis.
        /// </summary>
        public static string DissertationThesisDelete {
            get {
                return ResourceManager.GetString("DissertationThesisDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really wish to delete your chosen dissertation topic?.
        /// </summary>
        public static string DissertationThesisDeleteConfirmation {
            get {
                return ResourceManager.GetString("DissertationThesisDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed problem description.
        /// </summary>
        public static string DissertationThesisDescription {
            get {
                return ResourceManager.GetString("DissertationThesisDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a description of the problem!.
        /// </summary>
        public static string DissertationThesisDescriptionError {
            get {
                return ResourceManager.GetString("DissertationThesisDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it possible to develop a thesis in English?.
        /// </summary>
        public static string DissertationThesisEnglish {
            get {
                return ResourceManager.GetString("DissertationThesisEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending dissertation theses.
        /// </summary>
        public static string DissertationThesisPending {
            get {
                return ResourceManager.GetString("DissertationThesisPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctoral study thesis proposal.
        /// </summary>
        public static string DissertationThesisProposal {
            get {
                return ResourceManager.GetString("DissertationThesisProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The research task, which will include the thesis to be addressed.
        /// </summary>
        public static string DissertationThesisResearchTask {
            get {
                return ResourceManager.GetString("DissertationThesisResearchTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to assign a research task.
        /// </summary>
        public static string DissertationThesisResearchTaskError {
            get {
                return ResourceManager.GetString("DissertationThesisResearchTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected scientific contribution (algorithms, methodologies, ...).
        /// </summary>
        public static string DissertationThesisScientificContribution {
            get {
                return ResourceManager.GetString("DissertationThesisScientificContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to specify the expected scientific contribution!.
        /// </summary>
        public static string DissertationThesisScientificContributionError {
            get {
                return ResourceManager.GetString("DissertationThesisScientificContributionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended practice of scientific research.
        /// </summary>
        public static string DissertationThesisScientificProgress {
            get {
                return ResourceManager.GetString("DissertationThesisScientificProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to specify the recommended procedure for scientific research!.
        /// </summary>
        public static string DissertationThesisScientificProgressError {
            get {
                return ResourceManager.GetString("DissertationThesisScientificProgressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results to date of the solution at the training site, including references to available resources.
        /// </summary>
        public static string DissertationThesisSolutionResults {
            get {
                return ResourceManager.GetString("DissertationThesisSolutionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to submit the results of the solution so far at the training site!.
        /// </summary>
        public static string DissertationThesisSolutionResultsError {
            get {
                return ResourceManager.GetString("DissertationThesisSolutionResultsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List the literature in the same style as it is displayed in the University Library of the University of Žilina..
        /// </summary>
        public static string DissertationThesisSolutionResultsInfo {
            get {
                return ResourceManager.GetString("DissertationThesisSolutionResultsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissertation thesis title.
        /// </summary>
        public static string DissertationThesisTitle {
            get {
                return ResourceManager.GetString("DissertationThesisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a topic title!.
        /// </summary>
        public static string DissertationThesisTitleError {
            get {
                return ResourceManager.GetString("DissertationThesisTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrol.
        /// </summary>
        public static string Enrol {
            get {
                return ResourceManager.GetString("Enrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already enrolled for a dissertation thesis..
        /// </summary>
        public static string EnrolError {
            get {
                return ResourceManager.GetString("EnrolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externals.
        /// </summary>
        public static string Externals {
            get {
                return ResourceManager.GetString("Externals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find thesis.
        /// </summary>
        public static string FindThesis {
            get {
                return ResourceManager.GetString("FindThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your study easier..
        /// </summary>
        public static string HomeHeading {
            get {
                return ResourceManager.GetString("HomeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up and put the paperwork behind you!.
        /// </summary>
        public static string HomeSubheading {
            get {
                return ResourceManager.GetString("HomeSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number.
        /// </summary>
        public static string HouseNumber {
            get {
                return ResourceManager.GetString("HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual plan.
        /// </summary>
        public static string IndividualPlan {
            get {
                return ResourceManager.GetString("IndividualPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add individual plan.
        /// </summary>
        public static string IndividualPlanAdd {
            get {
                return ResourceManager.GetString("IndividualPlanAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended additional elective subjects.
        /// </summary>
        public static string IndividualPlanAdditionalSubjectsInfo {
            get {
                return ResourceManager.GetString("IndividualPlanAdditionalSubjectsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create individual plan.
        /// </summary>
        public static string IndividualPlanCreate {
            get {
                return ResourceManager.GetString("IndividualPlanCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete individual plan.
        /// </summary>
        public static string IndividualPlanDelete {
            get {
                return ResourceManager.GetString("IndividualPlanDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected individual plan?.
        /// </summary>
        public static string IndividualPlanDeleteConfirmation {
            get {
                return ResourceManager.GetString("IndividualPlanDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application deadline.
        /// </summary>
        public static string IndividualPlanDissertationExamDate {
            get {
                return ResourceManager.GetString("IndividualPlanDissertationExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the application deadline!.
        /// </summary>
        public static string IndividualPlanDissertationExamDateError {
            get {
                return ResourceManager.GetString("IndividualPlanDissertationExamDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deadline for submitting the application for the dissertation examination, including the submission of the written dissertation for the dissertation exam (usually the first half of September in the 2nd year).
        /// </summary>
        public static string IndividualPlanDissertationExamDateInfo {
            get {
                return ResourceManager.GetString("IndividualPlanDissertationExamDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission deadline.
        /// </summary>
        public static string IndividualPlanDissertationSubmissionDate {
            get {
                return ResourceManager.GetString("IndividualPlanDissertationSubmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to specify the submission date!.
        /// </summary>
        public static string IndividualPlanDissertationSubmissionDateError {
            get {
                return ResourceManager.GetString("IndividualPlanDissertationSubmissionDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissertation submission date (usually April in the year of graduation).
        /// </summary>
        public static string IndividualPlanDissertationSubmissionDateInfo {
            get {
                return ResourceManager.GetString("IndividualPlanDissertationSubmissionDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual plan edit.
        /// </summary>
        public static string IndividualPlanEdit {
            get {
                return ResourceManager.GetString("IndividualPlanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have profile information filled in!.
        /// </summary>
        public static string IndividualPlanError {
            get {
                return ResourceManager.GetString("IndividualPlanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not yet been assigned an individual plan..
        /// </summary>
        public static string IndividualPlanMissing {
            get {
                return ResourceManager.GetString("IndividualPlanMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual plans.
        /// </summary>
        public static string IndividualPlans {
            get {
                return ResourceManager.GetString("IndividualPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and surname, title.
        /// </summary>
        public static string IndividualPlanStudent {
            get {
                return ResourceManager.GetString("IndividualPlanStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to select a student!.
        /// </summary>
        public static string IndividualPlanStudentError {
            get {
                return ResourceManager.GetString("IndividualPlanStudentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of graduation.
        /// </summary>
        public static string IndividualPlanStudyEndDate {
            get {
                return ResourceManager.GetString("IndividualPlanStudyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to specify the date of graduation!.
        /// </summary>
        public static string IndividualPlanStudyEndDateError {
            get {
                return ResourceManager.GetString("IndividualPlanStudyEndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of completion of doctoral studies, including the defence of the dissertation (usually 31.8. after 3 years of study for internal doctoral students and after 4 years for external doctoral students).
        /// </summary>
        public static string IndividualPlanStudyEndDateInfo {
            get {
                return ResourceManager.GetString("IndividualPlanStudyEndDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry to doctoral studies.
        /// </summary>
        public static string IndividualPlanStudyStartDate {
            get {
                return ResourceManager.GetString("IndividualPlanStudyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to enter the date of arrival!.
        /// </summary>
        public static string IndividualPlanStudyStartDateError {
            get {
                return ResourceManager.GetString("IndividualPlanStudyStartDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to choose a subject!.
        /// </summary>
        public static string IndividualPlanSubjectError {
            get {
                return ResourceManager.GetString("IndividualPlanSubjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects with thematic headings for the dissertation examination.
        /// </summary>
        public static string IndividualPlanSubjectsInfo {
            get {
                return ResourceManager.GetString("IndividualPlanSubjectsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissertation theses.
        /// </summary>
        public static string IndividualPlanThesis {
            get {
                return ResourceManager.GetString("IndividualPlanThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not assigned a dissertation topic!.
        /// </summary>
        public static string IndividualPlanThesisError {
            get {
                return ResourceManager.GetString("IndividualPlanThesisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic of the written part of the dissertation examination.
        /// </summary>
        public static string IndividualPlanThesisInfo {
            get {
                return ResourceManager.GetString("IndividualPlanThesisInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctoral student&apos;s individual study plan.
        /// </summary>
        public static string IndividualPlanTitle {
            get {
                return ResourceManager.GetString("IndividualPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest.
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP Users.
        /// </summary>
        public static string LdapUsers {
            get {
                return ResourceManager.GetString("LdapUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login required.
        /// </summary>
        public static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged in!.
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More informations.
        /// </summary>
        public static string MoreInformations {
            get {
                return ResourceManager.GetString("MoreInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the sidebar for navigation..
        /// </summary>
        public static string NavigationInfo {
            get {
                return ResourceManager.GetString("NavigationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not approved.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy.
        /// </summary>
        public static string Occupancy {
            get {
                return ResourceManager.GetString("Occupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string OccupancyAvailable {
            get {
                return ResourceManager.GetString("OccupancyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        public static string OccupancyOccupied {
            get {
                return ResourceManager.GetString("OccupancyOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember login.
        /// </summary>
        public static string RememberLogin {
            get {
                return ResourceManager.GetString("RememberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        public static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research type.
        /// </summary>
        public static string ResearchType {
            get {
                return ResourceManager.GetString("ResearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied research.
        /// </summary>
        public static string ResearchTypeApplied {
            get {
                return ResourceManager.GetString("ResearchTypeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied research and experimental development.
        /// </summary>
        public static string ResearchTypeAppliedExperimental {
            get {
                return ResourceManager.GetString("ResearchTypeAppliedExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic research.
        /// </summary>
        public static string ResearchTypeBasic {
            get {
                return ResourceManager.GetString("ResearchTypeBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to choose the research type!.
        /// </summary>
        public static string ResearchTypeError {
            get {
                return ResourceManager.GetString("ResearchTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the type of research in which the thesis will be addressed..
        /// </summary>
        public static string ResearchTypeInfo {
            get {
                return ResourceManager.GetString("ResearchTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School year.
        /// </summary>
        public static string SchoolYear {
            get {
                return ResourceManager.GetString("SchoolYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External sign in.
        /// </summary>
        public static string SignInExternal {
            get {
                return ResourceManager.GetString("SignInExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string SignInExternalForgottenPassword {
            get {
                return ResourceManager.GetString("SignInExternalForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string SignInExternalMessage {
            get {
                return ResourceManager.GetString("SignInExternalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend the confirmation email..
        /// </summary>
        public static string SignInExternalResendEmail {
            get {
                return ResourceManager.GetString("SignInExternalResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string SignInExternalService {
            get {
                return ResourceManager.GetString("SignInExternalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login for extern..
        /// </summary>
        public static string SignInLdapLink {
            get {
                return ResourceManager.GetString("SignInLdapLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your LDAP account to sign in..
        /// </summary>
        public static string SignInLdapMessage {
            get {
                return ResourceManager.GetString("SignInLdapMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration link has expired!.
        /// </summary>
        public static string SignUpExpired {
            get {
                return ResourceManager.GetString("SignUpExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string SignUpMessage {
            get {
                return ResourceManager.GetString("SignUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to register..
        /// </summary>
        public static string SignUpService {
            get {
                return ResourceManager.GetString("SignUpService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add student.
        /// </summary>
        public static string StudentAdd {
            get {
                return ResourceManager.GetString("StudentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit doctoral student.
        /// </summary>
        public static string StudentEdit {
            get {
                return ResourceManager.GetString("StudentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student email.
        /// </summary>
        public static string StudentEmail {
            get {
                return ResourceManager.GetString("StudentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student name.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctoral students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study field.
        /// </summary>
        public static string StudyField {
            get {
                return ResourceManager.GetString("StudyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study form.
        /// </summary>
        public static string StudyForm {
            get {
                return ResourceManager.GetString("StudyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string StudyFormDaily {
            get {
                return ResourceManager.GetString("StudyFormDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string StudyFormExternal {
            get {
                return ResourceManager.GetString("StudyFormExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study informations.
        /// </summary>
        public static string StudyInformations {
            get {
                return ResourceManager.GetString("StudyInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study part.
        /// </summary>
        public static string StudyPart {
            get {
                return ResourceManager.GetString("StudyPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study program.
        /// </summary>
        public static string StudyProgram {
            get {
                return ResourceManager.GetString("StudyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to choose a study program!.
        /// </summary>
        public static string StudyProgramError {
            get {
                return ResourceManager.GetString("StudyProgramError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor email.
        /// </summary>
        public static string SupervisorEmail {
            get {
                return ResourceManager.GetString("SupervisorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to choose a supervisor!.
        /// </summary>
        public static string SupervisorError {
            get {
                return ResourceManager.GetString("SupervisorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor name.
        /// </summary>
        public static string SupervisorName {
            get {
                return ResourceManager.GetString("SupervisorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor specialist.
        /// </summary>
        public static string SupervisorSpecialist {
            get {
                return ResourceManager.GetString("SupervisorSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your assigned dissertation thesis is:.
        /// </summary>
        public static string ThesisStudentInfo {
            get {
                return ResourceManager.GetString("ThesisStudentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissertation thesis, that you are interested in:.
        /// </summary>
        public static string ThesisStudentInterestInfo {
            get {
                return ResourceManager.GetString("ThesisStudentInterestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string UserAdd {
            get {
                return ResourceManager.GetString("UserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create address.
        /// </summary>
        public static string UserCreateAddress {
            get {
                return ResourceManager.GetString("UserCreateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user.
        /// </summary>
        public static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected user?.
        /// </summary>
        public static string UserDeleteConfirmation {
            get {
                return ResourceManager.GetString("UserDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add users.
        /// </summary>
        public static string UsersAdd {
            get {
                return ResourceManager.GetString("UsersAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
